version: "3.9"

services:
  django:
    image: project2
    container_name: project2_container
    volumes:
      - /home/scott/django-static:/app/staticfiles
      - /home/scott/django-data:/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    stdin_open: true
    tty: true
