# Generated by Django 5.1.4 on 2025-02-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_sysdata_delete_voltagedata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sysdata',
            constraint=models.UniqueConstraint(fields=('user', 'system_name'), name='no duplicate sysnames per user'),
        ),
    ]
